theme: jekyll-theme-minimal
title: Welcome to the Akamai Nook development page!
description: The Akamai Nook is an application that allows students to find their favorite study spots. This project is made by students for students. This site will update constantly as the project develops. Stay tuned!
